name: CyberReader Summarization Auto Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/autoTest.yml'
      - '**/*.py'
      - 'main.py'

  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/autoTest.yml'
      - '**/*.py'
      - 'main.py'

jobs:
  YouTube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate config.yaml
        run: |
          python test/gen_config.py gpt-3.5-turbo-16k ${{ secrets.OPENAI_API_KEY }} tmp result https://www.youtube.com/watch?v=NIDs4lLYCLI
      - name: Summariz YouTube Video
        run: |
          python main.py --auto_test
      - name: Upload result to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result

  VideoUrl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate config.yaml
        run: |
          python test/gen_config.py gpt-3.5-turbo-16k ${{ secrets.OPENAI_API_KEY }} tmp result https://streaming.cle.ust.hk/media/RPG-common-curriculum/Unit-1-foundation/1-1-Welcome.mp4
      - name: Summariz Video Url
        run: |
          python main.py --auto_test
      - name: Upload result to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result

  m3u8Url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate config.yaml
        run: |
          python test/gen_config.py gpt-3.5-turbo-16k ${{ secrets.OPENAI_API_KEY }} tmp result https://1500023114.vod-qcloud.com/183bcc5avodtranshk1500023114/8e2a75dc5576678021889436837/video_1446006_0.m3u8
      - name: Summariz m3u8 Video Url
        run: |
          python main.py --auto_test
      - name: Upload result to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result